apm-nightly install formatter
apm-nightly install intentions
apm-nightly install linter-rubocop
apm-nightly install atom-ember-template-lint
apm-nightly install busy-signal
apm-nightly install formatter-json
apm-nightly install language-terraform
apm-nightly install linter-stylelint
apm-nightly install teletype
apm-nightly install atom-handlebars
apm-nightly install ember-snippets
apm-nightly install gpp-compiler
apm-nightly install linter
apm-nightly install linter-ui-default
apm-nightly install terraform-lookup
apm-nightly install file-icons
apm-nightly install ide-typescript
apm-nightly install linter-eslint
apm-nightly install linter-ui-touchbar
apm-nightly install touchbar-registry
